import React from 'react'
import { Link } from 'react-router-dom'
import Navbar from '../components/Navbar'

const LAST_UPDATED = 'August 11, 2026'
const CONTACT_EMAIL = 'mayankkotla5@gmail.com'

function Section({ title, children }) {
  return (
    <section>
      <h2 className="text-white font-semibold text-lg mb-2.5">{title}</h2>
      <div className="space-y-3">{children}</div>
    </section>
  )
}

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-app-bg text-white">
      <Navbar />
      <div className="max-w-3xl mx-auto px-6 pt-28 pb-24">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-gray-500 text-sm mb-10">Last updated {LAST_UPDATED}</p>

        <div className="space-y-9 text-gray-400 text-sm leading-relaxed">
          <Section title="1. Acceptance of Terms">
            <p>By creating an account or using IgKnight, you agree to these Terms of Service and our{' '}
              <Link to="/privacy" className="text-ucf-gold hover:text-yellow-400 transition-colors duration-150">
                Privacy Policy
              </Link>. If you don't agree, please don't use the app.</p>
          </Section>

          <Section title="2. Eligibility">
            <p>IgKnight is exclusively for UCF students and requires a valid <code className="text-gray-300">@ucf.edu</code> email
              address to register.</p>
          </Section>

          <Section title="3. Your Account">
            <p>You're responsible for keeping your password secure and for all activity that happens under your
              account. Provide accurate information when you sign up, and let us know right away if you think your
              account has been compromised.</p>
          </Section>

          <Section title="4. Acceptable Use">
            <p>When using IgKnight, you agree not to:</p>
            <ul className="list-disc list-outside pl-5 space-y-1.5">
              <li>Harass, threaten, or abuse other users.</li>
              <li>Post spam, illegal content, or content that infringes someone else's rights.</li>
              <li>Impersonate another person or misrepresent your affiliation with UCF.</li>
              <li>Use KnightCheck or any group's shared materials to violate UCF's academic integrity policies —
                IgKnight is a study aid, not a substitute for following your course's and university's academic
                honesty rules.</li>
            </ul>
            <p>We reserve the right to remove content or suspend accounts that violate these terms.</p>
          </Section>

          <Section title="5. Your Content">
            <p>You retain ownership of anything you post — messages, files, notes, and questions you upload. By
              posting it in a group, you're granting the other members of that group the ability to view it, and
              you're granting IgKnight the ability to store and display it as part of running the app. You're
              solely responsible for content you share.</p>
          </Section>

          <Section title="6. Reporting & Moderation">
            <p>You can report a message for review, and you can block another user to hide their messages from
              your own view. A group's owner can remove members from that group or delete the group entirely.
              These tools exist to help keep the community civil, but we can't guarantee every issue will be
              caught or resolved immediately.</p>
          </Section>

          <Section title="7. AI-Generated Content">
            <p>KnightCheck quizzes are generated by an AI model (Anthropic's Claude) based on materials you and
              your group provide. AI-generated questions and answers can be inaccurate or incomplete — treat
              KnightCheck as a study aid, not an authoritative source, and always verify against your actual
              course materials.</p>
          </Section>

          <Section title="8. Third-Party Services">
            <p>IgKnight depends on third-party services (Supabase, Anthropic, Google, Sentry) to function. We
              aren't responsible for outages, errors, or data loss caused by those services being unavailable.</p>
          </Section>

          <Section title="9. Termination">
            <p>You can stop using IgKnight at any time, and you can permanently delete your own account whenever
              you like using the "Delete account" option in the account menu — no need to contact us. Deleting
              your account also deletes any groups you own, including their chat history, sessions, notes, and
              uploaded files, for everyone in them. This action is immediate and can't be undone. We may also
              suspend or terminate an account that violates these terms, at our discretion.</p>
          </Section>

          <Section title="10. Disclaimer of Warranties">
            <p>IgKnight is provided "as is," without warranties of any kind. We don't guarantee the app will be
              uninterrupted, error-free, or perfectly accurate — including KnightCheck's AI-generated content.</p>
          </Section>

          <Section title="11. Limitation of Liability">
            <p>To the fullest extent permitted by law, IgKnight and its creator aren't liable for any indirect,
              incidental, or consequential damages arising from your use of the app.</p>
          </Section>

          <Section title="12. Not Affiliated with UCF">
            <p>IgKnight is an independent, student-built project. It is not affiliated with, endorsed by, or
              operated by the University of Central Florida.</p>
          </Section>

          <Section title="13. Changes to These Terms">
            <p>We may update these terms from time to time. Continuing to use IgKnight after a change means you
              accept the updated terms.</p>
          </Section>

          <Section title="14. Contact">
            <p>Questions about these terms? Email{' '}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-ucf-gold hover:text-yellow-400 transition-colors duration-150">
                {CONTACT_EMAIL}
              </a>.</p>
          </Section>
        </div>

        <div className="mt-12 pt-8 border-t border-app-border">
          <Link to="/privacy" className="text-ucf-gold hover:text-yellow-400 text-sm font-medium transition-colors duration-150">
            Read the Privacy Policy →
          </Link>
        </div>
      </div>
    </div>
  )
}
